name: Generate and Push File
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: true 
      ref:
        description: 'Name of triggered repo'
        required: true
        default: 'main'
        type: string
      payload:
        description: 'Name of triggered repo'
        required: true
        default: 'ddddddddddddd'
        type: string        
        
       
jobs:
  generate-and-push:
    strategy:
      matrix:
        api:
          - petstore  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Extract JSON values and generate file
        id: generate-file
        run: |
          payload=$(echo "${{ github.event.ref }}" )
       
 #       run: |
 #         payload=$(echo "${{ github.event.payload }}" )
 #         value=$(echo "$payload" | jq -r '.spec.definition.value')
 #         filename=$(echo "$payload" | jq -r '.name')
 #         echo "$value" > "$filename.yaml"
 #     - name: Commit and push changes
 #       run: |
 #         git config --global user.email "action@github.com"
 #         git config --global user.name "GitHub Action"
 #         git add "apis/${{ matrix.api }}/$filename.yaml"
 #         git commit -m "Generate and push file"
 #         git push origin main          