name: Generate and Push File

on:
  push:
    branches:
      - main

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
